### ISSUE TITLE
Shutdown Not Called on Record Processors when MultiLangDaemon is Terminated

### ISSUE THREAD

**Issue by eyesoftime** [awslabs/amazon-kinesis-client#35] opened 2015-08-05 12:30 UTC
When running the daemon (from command-line for example), upon terminating the process (Ctrl+C or SIGTERM) it exits and doesn't call shutdown() on child processes. It doesn't allow child processes to terminate cleanly by checkpointing their state. Is this intentional or something that's just not been implemented (yet)?

**Comment by gharikum** [comment] 2015-09-10 22:42
Apologize for this. A few users have reported similar problems. We are working on clean shutdown mechanics for the KCL. But don't have a release date yet.

**Comment by abonhomme** [comment] 2016-02-09 07:52
Just curious if there's an ETA on this one yet?  thanks!

**Comment by darkcrawler01** [comment] 2016-02-09 08:00
+1

**Comment by daskruegge** [comment] 2016-02-25 10:08
+1

**Comment by findchris** [comment] 2016-03-03 00:21
@gharikum - Any movement here?  I see no new KCL development for about 5 months now.

**Comment by pfifer** [comment] 2017-01-23 19:56
Thanks for reporting this.  It does appear this affects many customers, and I'll be investigating adding a shutdown hook that should help this.  It won't fix cases where the JVM doesn't get a chance to shutdown normally e.g. kill -9.

**Comment by ewalker11** [comment] 2017-04-18 06:27
We could really use this. Any update?

**Comment by jgrier** [comment] 2017-09-06 20:05
It looks like this was fixed here, no?  https://github.com/awslabs/amazon-kinesis-client/commit/5a8bac23c613a307f22611c2f1a289347e893067

Should this issue be closed?

**Comment by pfifer** [comment] 2017-09-06 20:12
Thanks for catching this, I'll close it now.  

For posterity:
This was fixed in #174 with the addition of graceful shutdown for MultiLang Daemon clients.

Let us know if you run into any problems.

**Closed by pfifer** 2017-09-06 20:12 UTC
Labels: enhancement, multi lang daemon

**Comment by dhruvpanwar95** [comment] 2018-04-06 08:46
When i stop application using ctrl+c,shutdown requested method of I shutdown Aware doesn't get called

**Comment by pfifer** [comment] 2018-04-06 17:07
This change only affected the multilang daemon clients, and not the general Java KCL.  If you're using Java you can install the shutdown hook yourself.  I don't want to install it for customers using Java, as it could cause unexpected behavior.

**Comment by mitaligit** [comment] 2022-02-18 20:40
Does the shutdownRequested work for Java KCL as well now?

**Comment by hsingh124** [comment] 2024-08-12 06:17
Hey, I am working with the multilang daemon in php. I try to terminate the java process with SIGINT but get a timeout exception whenever the shutdown happens. Can I get some help with this? Here are the logs:

```
2024-08-12 18:06:09,299 [Thread-1] INFO  s.a.k.multilang.MultiLangDaemon [NONE] - Process terminated, will initiate shutdown. 
2024-08-12 18:06:09,312 [Thread-1] ERROR s.a.k.multilang.MultiLangDaemon [NONE] - Encountered an error during shutdown. 
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1892)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2027)
	at software.amazon.kinesis.multilang.MultiLangDaemon.lambda$setupShutdownHook$0(MultiLangDaemon.java:183)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Thanks!
