### ISSUE TITLE
Kinesis graceful shutdown for a simple KCL 2.0 consumer not working

### ISSUE THREAD

**Issue by swaranga** [awslabs/amazon-kinesis-client#616] opened 2019-09-24 22:27 UTC
We are using the KCL 2.0 to utilize the enhanced fan-out feature to consume a Kinesis stream but we see the application not being able to shutdown gracefully. The ShardRecordProcessor does return successfully on shutdown but the GracefulShutdownCallable's Future returns false. Here is a minimal application that demonstrates the problem: https://pastebin.com/LhLvfkrs - note that this is even more minimal than the example in the documentation (there is no producer and the process implementation is empty. Is the false returned from the Future a red herring?

Here is the log of the run: https://pastebin.com/2TSHxHEZ - (see line 38).

I also notice that leaseLost is called on the ShardRecordProcessor for a Shutdown request (line 33). Is that the right behavior?

**Comment by aggarwal** [comment] 2019-09-27 05:22
I suspect that a shard consumer is stuck in failure loop and holding up the graceful shutdown. Try setting a breakpoint in the following code to confirm: https://github.com/awslabs/amazon-kinesis-client/blob/98b016276b0387ed77d1049c706673ad1fbf6b22/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumer.java#L348-L378

You can also gather more information by enabling debug logging. Specifically, if a task is stuck in a failure loop, the following code should print the appropriate exception to the logs:
https://github.com/awslabs/amazon-kinesis-client/blob/98b016276b0387ed77d1049c706673ad1fbf6b22/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumer.java#L337-L346

I think KCL 1.x has the same issue.

**Comment by BobbyJohansen** [comment] 2019-10-09 21:17
https://github.com/awslabs/amazon-kinesis-client/pull/538

**Comment by swaranga** [comment] 2020-02-25 08:22
Ping any updates on this? I gave you a small self-contained program that demonstrates the issue. Can this be prioritized?

**Comment by jrehwaldt** [comment] 2020-06-03 09:10
We are seeing the exact same problem (and log) using polling retrieval strategy. I placed breakpoints in the mentioned places and there was nothing unusual visible.

From the message 
```
Shutdown completed, but shutdownCompleteLatch still had outstanding 1 with a current value of 1. shutdownComplete: false -- Consumer Map: 0
```
it reproducible takes around one second for the Worker/Scheduler loop to start final shutdown (`Starting worker's final shutdown.`).

```

**Comment by jrehwaldt** [comment] 2020-06-03 10:41
@aggarwal What's the reason for `|| context.scheduler().shardInfoShardConsumerMap().isEmpty()` here?

https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/GracefulShutdownCoordinator.java#L46-L48

To fix the issue at hand the condition above would need to be split:
1. Wait for `shardInfoShardConsumerMap().isEmpty()` to get empty (if desired at all)
2. Wait for Scheduler shutdown (`context.scheduler().shutdownComplete()`) for `shardConsumerDispatchPollIntervalMillis + delta`

I am assuming the condition under 1. is required for some particular scenario. Otherwise, it could be dropped altogether. Imho, `Scheduler.shouldShutdown` already checks the exact same condition and is a precodition for `Scheduler.shutdownComplete()` to return `true`.

**Comment by aggarwal** [comment] 2020-06-04 02:38
> To fix the issue at hand the condition above would need to be split:
> 
> 1. Wait for `shardInfoShardConsumerMap().isEmpty()` to get empty (if desired at all)
> 2. Wait for Scheduler shutdown (`context.scheduler().shutdownComplete()`) for `shardConsumerDispatchPollIntervalMillis + delta`
> 

@jrehwaldt, how does this fix the issue?

When `shardInfoShardConsumerMap().isEmpty()` returns `true`, it means that the scheduler does not have consumers left for any lease. At this point this scheduler likely does not have ownership over any lease.

It's been a while since I read this code.

**Comment by jrehwaldt** [comment] 2020-06-04 05:54
I believe it's a matter of when the shutdown is considered successful. If
> it means that the scheduler does not have consumers left for any lease.

is sufficient for successful shutdown, then the graceful shutdown future should return `true` instead of `false`. Otherwise, if proper shutdown of the Scheduler's executor and CloudWatch publisher is expected as well, the shutdown has to explicitly wait for this to happen.

The current implementation considers it enough to have no leases, but still reports to the clients _shutdown was not successful_. I'd argue the API has to decide.

> @jrehwaldt, how does this fix the issue?

In
https://github.com/awslabs/amazon-kinesis-client/blob/be1e3cd112facdc60e57defe6c9b8601240d1565/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/GracefulShutdownCoordinator.java#L135-L146
`outstanding` is non-zero. This is the case sinc not all Schedulers have counted down their latch. Two places exist for counting down:

1. Standard case:
  https://github.com/awslabs/amazon-kinesis-client/blob/be1e3cd112facdc60e57defe6c9b8601240d1565/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumerShutdownNotification.java#L78-L87
1. Edge case:
  https://github.com/awslabs/amazon-kinesis-client/blob/be1e3cd112facdc60e57defe6c9b8601240d1565/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java#L473-L481

Case 1 is triggered through the following flow:
1. https://github.com/awslabs/amazon-kinesis-client/blob/be1e3cd112facdc60e57defe6c9b8601240d1565/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ConsumerStates.java#L22-L84
1. `ConsumerState.ShutdownCompleteState.createTask()`
1. `ShardConsumerShutdownNotification.shutdownComplete()`
1. `<latch>.countDown()`

From the flow diagram we can see that `Shutting Down` state is a pre-condition for `Shutdown Complete`. The state `Shutting Down` is reached once the leases are lost
https://github.com/awslabs/amazon-kinesis-client/blob/be1e3cd112facdc60e57defe6c9b8601240d1565/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ConsumerStates.java#L107-L108

Considering the graceful shutdown condition in the light of this flow means shutdown of Schedulers will only start once all leases are lost, which - if I understand your statement correct - roughly translates into `shardInfoShardConsumerMap().isEmpty() == true`. With default configuration the Scheduler's main loop sleeps 1s (`shardConsumerDispatchPollIntervalMillis`) before it will check for shutdown request again. This means it takes rather long until the Scheduler figures out it'll have to shut down.

That's my understanding 🤷

**Comment by xsahban** [comment] 2020-12-08 07:36
Do we have any updates on this issue?
getting following logs after a graceful shutdown called

```
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
[pool-20-thread-1] INFO software.amazon.kinesis.leases.LeaseCleanupManager - Number of pending leases to clean before the scan : 0
```

**Comment by swaranga** [comment] 2021-08-13 22:57
Can we get an update on this? Has this been fixed? Why does it take 9 months to get an update on the recommended SDK for your flagship product?

**Comment by tomermayost** [comment] 2022-06-17 10:57
we are having the same problem: Shutdown completed, but shutdownCompleteLatch still had outstanding 2 with a current value of 2. shutdownComplete: false -- Consumer Map: 0

**Comment by brunovoodoo** [comment] 2023-03-20 13:58
any updates on this?

**Comment by vincentvilo-aws** [comment] 2024-04-03 22:29
After diving into this issue, I found that `startGracefulShutdown` is returning false because the `shutdownCompleteLatch` is not counting down to zero. To be specific, the original code provided by the OP gets stuck in [this loop](https://github.com/awslabs/amazon-kinesis-client/blob/7f1f243676c7303975e9fd96d5138c367425a171/amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/GracefulShutdownCoordinator.java#L127-L135) until the worker is finished shutting down. The worker finishes its shutdown while it’s in this block, and this causes `workerShutdownWithRemaining` to return true and, thus, `waitForRecordProcessors` to return false. In summary, there are two main reasons as to why `startGracefulShutdown` returns false:

1) The shutdownCompleteLatch must be decremented to avoid getting stuck in the loop.
2) The worker’s final shutdown needs to complete before returning the result of startGracefulShutdown.

The latest PR (#1302) addresses these issues.

For 1), we need to count down the shutdownCompleteLatch during the shutdown process. Originally, this was done in the task of the ShutdownCompleteState ([ref](https://github.com/awslabs/amazon-kinesis-client/blob/581d713815ef55d8578bd4d51527fe43a43bc72c/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ConsumerStates.java#L559-L563)), but in #1302 this line was moved to be executed during the ShutdownTask ([ref](https://github.com/awslabs/amazon-kinesis-client/blob/7f1f243676c7303975e9fd96d5138c367425a171/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShutdownTask.java#L155-L157)).

For 2), a `finalShutdownLatch` was introduced to the GracefulShutdownContext so that we wait for the finalShutdown to complete before returning.

I'll be closing this issue, but feel free to reopen it if you find that the PR does not address your issue.

**Closed by vincentvilo-aws** 2024-04-03 22:29 UTC
