### ISSUE TITLE
Publish lag for each kinesis consumer

### ISSUE THREAD

**Issue by akumariiit** [awslabs/amazon-kinesis-client#437] opened 2018-10-09 04:23 UTC
We have a kinesis stream which has multiple consumers. Our app is one of the consumer and we would like to do autoscaling based on lag. GetRecords.IteratorAgeMilliseconds gives the lag across all consumers, that makes it hard for us to find the lag for our one consumer, specially when one of the consumer is firehose lambda.
Can we get per consumer lag so that we can autoscale consumer based on that.

**Comment by vik7** [comment] 2018-10-09 04:31
+1

**Comment by jdmonter** [comment] 2018-10-09 11:34
Isn't this is a duplicate of #249 ? Could you +1 over there, too?

**Comment by pfifer** [comment] 2018-10-09 15:01
Are you asking about the Kinesis metrics?  How far behind a consumer should be provided as `SubscribeToShardEvent.MillisBehindLatest` for the consumer.  The [monitoring Amazon Kinesis guide](https://docs.aws.amazon.com/streams/latest/dev/monitoring-with-cloudwatch.html) can provide more detail.

If you have questions about the Kinesis service metrics please a thread on the [Amazon Kinesis Forums](https://forums.aws.amazon.com/forum.jspa?forumID=169)

Feel free to reopen this if you additional questions.

**Closed by pfifer** 2018-10-09 15:01 UTC
Labels: question
