### ISSUE TITLE
Initial checkpoint TRIM_HORIZON forces exception "Could not checkpoint at extended sequence number"

### ISSUE THREAD

**Issue by miketehranian** [awslabs/amazon-kinesis-client#37] opened 2015-08-23 23:26 UTC
Immediately after the KCL creates a new Lease Coordination table I have the following state:

leaseKey | checkpoint | checkpointSubSequenceNumber
------------- | -------------- | -------------------------------------------------------
shardId-000000000000 | TRIM_HORIZON | 0

**InitializeTask** has the following code:
```java
recordProcessorCheckpointer.setLargestPermittedCheckpointValue(initialCheckpoint);
recordProcessorCheckpointer.setInitialCheckpointValue(initialCheckpoint);
```

Which guarantees that an exception will be thrown in **RecordProcessorCheckpointer** at the following if-statement when processing the first incoming record:
```java
if ((lastCheckpointValue.compareTo(newCheckpoint) <= 0) &&
newCheckpoint.compareTo(largestPermittedCheckpointValue) <= 0) { 
    ...
} else {
throw new IllegalArgumentException(String.format(
    "Could not checkpoint at extended sequence number %s as it did not fall into acceptable range "
    + "between the last checkpoint %s and the greatest extended sequence number passed to this "
    + "record processor %s",
    newCheckpoint, this.lastCheckpointValue, this.largestPermittedCheckpointValue));
}

```

Here's the full stack-trace:

```java
! java.lang.IllegalArgumentException: Could not checkpoint at extended sequence number {SequenceNumber: 49553736826478174424587116688541051968144701038643904514,SubsequenceNumber: 0} as it did not fall into acceptable range between the last checkpoint {SequenceNumber: TRIM_HORIZON,SubsequenceNumber: 0} and the greatest extended sequence number passed to this record processor {SequenceNumber: TRIM_HORIZON,SubsequenceNumber: 0}
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.checkpoint(RecordProcessorCheckpointer.java:139) ~[amazon-kinesis-client-1.6.0.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.checkpoint(RecordProcessorCheckpointer.java:103) ~[amazon-kinesis-client-1.6.0.jar:na]
! at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.emit(KinesisConnectorRecordProcessor.java:178) ~[amazon-kinesis-connectors-1.2.0.jar:na]
! at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.processRecords(KinesisConnectorRecordProcessor.java:136) ~[amazon-kinesis-connectors-1.2.0.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42) ~[amazon-kinesis-client-1.6.0.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:168) ~[amazon-kinesis-client-1.6.0.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.6.0.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.6.0.jar:na]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

**Comment by manango** [comment] 2015-09-24 01:51
@miketehranian, thanks for reporting the issue. The root cause of the issue seems to be #40. KCL was incorrectly setting largest permitted checkpoint value to last checkpointed value when no records were received with GetRecords API call. The issue has been fixed with the KCL 1.6.1 release. Feel free to reopen the issue if you still run into this error.

**Closed by manango** 2015-09-24 01:51 UTC
